name: Comosite Action Example
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: load and Cache dependencies
              id: cache-deps
              uses: ./.github/actions/cached-deps
              with:
                caching: 'false'
            - name: Output Info
              run: echo "Cache Used? ${{steps.cache-deps.outputs.used-cache}}"
            - name: Lint code
              run: npm run lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: load and Cache dependencies
              uses: ./.github/actions/cached-deps
            - name: Test code
              run: npm run test
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              run: echo "Deploy.. "
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Run custom action
              uses: ./.github/actions/deploy-s3-javascript