name: Deploy Project
on:  
  push:
    branches:
      - master
jobs:
  lint:
      runs-on: windows-latest
      steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Setup NodeJs
        uses:  actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependecies
        run: npm ci
      - name: Linting
        run : npm run lint
  test:
    needs: lint
    runs-on: windows-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Setup NodeJs
        uses:  actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependecies
        run: npm ci
      - name: Runt tests
        run : npm test
  build:
    needs: test
    runs-on: windows-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Setup NodeJs
        uses:  actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependecies
        run: npm ci
      - name: Build Project
        run : npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            dist
            package.json
  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Deploy
        run: echo "Deploying...."
