name: Check security
on:
    issues:
        types:
            - opened
jobs:
    Check:
        runs-on: ubuntu-latest
        env:
            Title: ${{ github.event.issue.title}}
        steps:
            - name: Print Title
              run: |
                if [[ "$Title" == *"bug"* ]]; then
                echo "Issue is about a bug!"
                else
                echo "Issue is not about a bug"
                fi
            - name: Assign Label
              if: contains(github.event.issue.title, 'bug')
              run: |
                curl -X POST \
                --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
                -H 'authorization: Bearer ${{secrets.GITHUB_TOKEN }}' \
                -H 'content-type: application/josn' \
                -d '{
                    "labels": ["bug"]
                  }' \
                --fail
